### ISSUE TITLE
How-To Example Incorrect?

### ISSUE THREAD

**Issue by thepaulmacca** [kintoandar/pre-commit#10]
I'm looking at the How-To and in Step 2, the example is this:

```yaml
cat <<EOF > .pre-commit-config.yaml
- repo: git://github.com/kintoandar/pre-commit.git
  sha: v2.1.2
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: prometheus_check_rules
  - id: prometheus_check_config
EOF
```

Shouldn't `sha` be `rev` like other hooks?

Thanks
